---
title: "Bad day Counter"
author: ''
date: "2023-11-05"
slug: "bad-day-counter"
categories: []
tags: []
---

- 11/5/2023, this is a bad day for me. But I know the Chris guy bullied other students in the class and I was very mad. Obviously he learned the curse words from Chris.

- 12/14/2023, this is a bad day for me. Ian did not want to go to bed at 10:03pm; I said you could survey all of your peers around our house; he said there're only three kids. I said you could survey your classmates tomorrow, he said Francisco went to bed after 10pm. I set up the three rules

1. go to bed by 9:30pm everyday;

2. no food and video at the same time;

3. at least one exercise a day.

- 2/24/2024. One day before, he lied to his mom that he put the egg into the toilet. The reason is that the egg is mixed with milk. Several days before this, he just changed the date of an old composition and lied to his mom as the new one. With the two lies, especially the second one, I was very upset. And today, he keeps playing with mom's cellphone while eating. I warmed him two time, but he cannot stop.

- 4/11/2024. He was reluctant to share with me anything about the music memory, and he hit me at least three times.

- 5/5/2024. We planned first play basketball at Anthony outdoor playground, and then swim on Genesis. But he did not follow the instructions of shooting. Finally, we only played basketball.

- 5/12/2024. When I got up, I saw him watching videos. He told he had been doing it for almost three hours.

- 8/27/2024. I asked him to say something about the trend of all the factor pair list of 48. He was so absent-minded: He just say "I don't know" twice-I was so upset!

- 10/10/2024. It's the flag football game vs. Eagles. I asked him to practice after the dinner and he refused. He also turned my suggestion of swim for one hour before the same since it would start at 7pm. I asked him to turn off the light in the family room and he said "It's your job instead of mine". I asked him to change the outfit and he refused again.

- 1/13/2025. It's the next day after he attended the True Blue Igloo and he earned the first place in 100 Breast. We're very happy, but he did not eat too much for dinner before swimming practice. I was a little upset, but I controlled my anger then. After swimming, he was Hungary and asked for some food. I let him alone eating, but he finished so little while he was reading a book. I was so upset.

