---
title: Ian's history about 9-11
author: ''
date: '2022-09-11'
slug: ian-s-history-about-9-11
categories: []
tags: []
---

## 9/11

In the morning, he asks me "Is today 9/11?"; after I say "yes", he says "then today is the $21^{th}$ anniversary of 9-11!" I just realize that he is right: 21 years have passed since the big event happened in 2001. I am very curious about how he knows that and ask him "How do you know it?". 

"Ms. Mortron was 4 years old when 9/11 happened; now, she is 25."Ms. Mortron is his main teacher. At that moment, I really appreciate Ms. Mortron's teaching history to the kids on such a nice way. To continue, I ask him "how much do you know about 9/11?"

He then shares with me that two airplanes hit the Twin Tower and the third one tried to hit the Pentagon but failed. 

"Who did the 9/11?" 

"That is a good question, what did Ms. Mortron say about it?"

"I forgot to ask her the question in class!" then I have to tell him something like alqueda. What he says next really shocks me.

"they're bad guys, but they died also since the whole plane crashed."

He asks me "what happens to the Twin Tower now?"

"They're cleared off and now there is memorial museum for 9/11" I plan to find the paper from Raz-kids for him to read.

"Is the Empire State Building still there?"

After I say "yes", he tells me something about the building. He also shares me with a story about Ms. Mortron: her grandma got hit in the head by a flying quater from Empire State Building and died. I don't think that is true, but I cannot confirm ti by asking Ms. Mortron next time when I meet her?


## my comments

1. Ms. Mortron is a great teacher.

2. actually, I do not know too much about 9/11: I even thought there was only one airplane hitting the Twin Tower. But I remember exactly the day when I first got know the event by VOA radio.

2. last years, it was 20th anniversary and a lots of programs were going on about it. but this year,not too much; plus, I am very busy and get no time to listen to NPR.