---
title: "Fraternity"
author: ''
date: "2023-01-30"
output: pdf_document
categories: []
tags: []
slug: fraternity
---

Last Wednesday, PJ gave me an [invitation](/pdf/PJFraternilty.pdf) for the open house; I decide to go there after I confirm that I could go with Ian. I talk with Ian after I get home, and he turned it down at first. But I persuaded him to go there since he could get to know the college life ahead of time.

Finally, Ian and I went there, with a box of donuts as gift. I took me a while to find the location and the it is very cold outside. But it is really warm in side: there are 41 people living inside the building; the rent is about $8400 plus meal, which is cheaper than the regular dorm. Actually, the GPA has to above a limit before finally being admitted into the Fraternity house.

They call the house keeper "mom", which I feel really surprised. I have heard a lot about Fraternities, but this is my first time to get into one. The fercility is really good-they even have a proctor exam room and PJ's friend tells me that that's the room they ake the exam for the online courses during the .com. 

Ian is a little shy at first and even want to hide behind the door since he is the only child onsite. He gets better after a cookie. Both of us drink some special "tea", it is yellowish and tastes sour. PJ and I take a picture, and Ian refuses to join in. 