---
title: "When  can I sit beside you?"
author: ''
date: '2022-06-02'
slug: when-can-i-sit-beside-you
categories: []
tags: []
---
## 1. 
Ian asked me the question on our way to Genesis; I replied with 16. But he told me that he saw a 12-year old boy sitting on that seat. I said you could do that when you get that age. I shared my experience with him:

- When I was his age and I cannot wait to grow up. I was really into a razor with which my dad cut his beard. I even tried to use it on mine once.

- I asked him why he wanted to sit beside the driver's seat. He said he would have bigger leg room, with the air vent right in the front and could do more stuff.

## 2.

When we got to the Genesis, Ian wanted to play basketball first. We borrowed one ball from the front desk, but he found the ball was broken when we were half way to the stairs up to the second floor. So he went back to front desk and switch to another one. He told me that what if the baseball is the same side as basketball. "It is impossible, " he said, "for at least two reasons":

- it is too big to bat;

- it is too big to catch with the glove.

The basketball court was crowded and he played a little bit himself, with I am standing aside. He told me he got 4 shots in total.

## 3.

 He swam really well today and finished 15 laps in all. When he finished 9 laps, he went to the hot tub and was forced back to the pool to finish the rest 6 laps. He is faster than me in every style now, except with the buoy between the legs.
 
## 4.

On our way home, he quized me about two questions:

- What was the ancestor of chickens and pelican?

 His answer: T-rex, trisauratops
- What was the largest dinosaur on the land?

## 5. Answers I googled:
[chickens are closely related to dinosaurs. Among other kind of birds, chickens, including turkeys, are the closest one.](https://earthbuddies.net/are-chickens-really-the-closest-descendants-of-t-rex/)

A 68 million years old Tyrannosaurus Rex DNA was compared to DNA of 21 modern species of animals and from the analysis researchers found out that chickens are the closest one. 

Another prove of chickens’ close relationship with T-Rex is the finding of one feathery kind of dinosaur. About 85 million years ago, a dinosaur named Archaeopteryx roamed the earth. [Archaeopteryx](https://en.wikipedia.org/wiki/Archaeopteryx) is a close relative to T-Rex and velociraptors.

- [Mastodon](https://en.wikipedia.org/wiki/Mastodon) were most similar to modern day elephants

- [Theropoda](https://en.wikipedia.org/wiki/Theropoda)

Tyrannosaurus was for many decades the largest known theropod and best known to the general public. Since its discovery, however, a number of other giant carnivorous dinosaurs have been described, including Spinosaurus, Carcharodontosaurus, and Giganotosaurus.[17] 