---
title: "Sandy Hook"
author: ''
date: "2022-12-14"
slug: "sandy-hook"
categories: []
tags: []
---

## [NPR remembers the victims of the Sandy Hook Elementary School shooting ten years later.](https://www.npr.org/2022/12/14/1142893579/remembering-sandy-hook-shooting-victims-ten-years-later) 

I was cooking when I listened to the radio. 那些受害者的家长真的很坚强，可以想象他们这十年是怎么过来的！

## Transcript

ARI SHAPIRO, HOST:

Today marks 10 years since 20 first-grade students and six staff were killed at Sandy Hook Elementary School in Newtown, Conn. It was a mass shooting that shook the country and inspired a renewed wave of activism.

JUANA SUMMERS, HOST:

But rather than focus on that day as a singular event, we want to reflect on the lives of some of those who died that day, specifically four students whose parents shared with us how they want their children to be remembered.

SCARLETT LEWIS: Jesse was nonstop.

(SOUNDBITE OF MUSIC)

LEWIS: I feel like, in my life, I am dragging a lot of people around (laughter) behind me. I always have felt that. But Jesse was literally dragging me. It was pretty amazing.

JOANN BACON: Charlotte just kind of brought us out of our, I guess, our shells a little bit. For her 6th birthday, I asked her, I said, you know, Charlotte, what would you like to do? Do you want a birthday party, or do you want a experience? And she's like, oh, I want a experience, which is, you know, so like her (laughter). And so I said, what would you like to do? And she's like, I just want to go on to New York City and walk around and see what's happening. She did a lot of living in those six years.

NICOLE HOCKLEY: Dylan was definitely the center of our family, you know, possibly because he was the youngest, but more likely because of his autism. He wanted to be part of something. So, like, if the kids were playing kickball, you know, we'd roll the ball to him. And all the kids would be going, kick it, Dylan, kick it. He would kick it, and then he'd kind of sit down. And they'd be like, whoa, run to first base. And they would, like, run alongside with him. And he was just having the time of his life.

ALISSA PARKER: Emilie was a very spontaneous, fun-loving, creative being.

ROBBIE PARKER: And she could connect with people on their level for how young she was. That was really amazing. I remember one time we were at Costco and you're checking out and Emilie's talking, and then I realized she was talking to the worker at Costco that was, like, helping scan things and stuff like that. And they were having a conversation, and I realized this wasn't the first time they had met. Emilie had, like, created this bond. They had talked before, and she recognized her. And they kind of picked up right where they had left off before.

(SOUNDBITE OF MUSIC)

BACON: The day before she died, I had asked her, I said, Charlotte, can I braid your hair? So I braided her hair, and she went off to school. And she came home that night, and she was like, oh, Mommy. One of the little girls in her class said I looked so cute with my braids today. Will you braid my hair tomorrow? I said, oh, I'd love to. You know, I was so excited 'cause I'm like, well, she's not growing up too quickly (laughter). And so that's one of the memories that I really hold on to - is that the next morning I got to braid her hair again before she went off to school.

(SOUNDBITE OF MUSIC)

HOCKLEY: I'd been working to get him to have a liquid multivitamin every day. And he really didn't like the taste. And that morning was the very first day he actually drank the entire dose of multivitamins. And he was so proud of himself. He had this horrible grimace on his face because of the taste. But he was also so proud and, you know, flapping. He jumped and flapped a lot when he was happy.

LEWIS: Jesse's dad was picking him up at the end of the driveway. I walked Jesse out. I turned around to give Jesse a hug, and I noticed that he had written in the frost on the side of my car, I love you.

(SOUNDBITE OF MUSIC)

A PARKER: One of my last conversations with her, she was pointing to these flowers that we had painted on her wall, and she said, Mom, this one's pink with a blue center, and this one's blue with a pink center. Do you see it? And I was like, yeah. And she goes, Mom, they're connected. There's connections everywhere. Everything is connected. And those words were incredibly powerful to me. And I've always remembered them.

(SOUNDBITE OF MUSIC)

HOCKLEY: I think I'm almost in a little bit of shock that it's 10 years. It feels like it was so recent, you know, that he was just here. And yet a decade's gone, and I can't - I mean, I'm older. The people around me are older. And yet my boy is still 6, and I can't connect the dots in my head.

LEWIS: In some aspects, it seems like it was yesterday. And in others, it seems like it's been a lifetime.

BACON: The first few years we would go to the cemetery. And I found myself not wanting or not needing, I guess, maybe, to go to the cemetery as often as I used to. I guess I feel her in different places than there. As grief kind of evolves, the way that we remember her has, too.

(SOUNDBITE OF MUSIC)

HOCKLEY: I always go to a beach and just wander for a few hours and just reflect on Dylan. And, you know, that reflecting on him makes me smile, and it also makes me cry.

A PARKER: The days leading up to the anniversary are awful, but your body has a funny way of saying enough is enough. And typically, by the time that the anniversary rolls around, my body says, it's enough. And I usually feel pretty numb that day. And that reprieve I look at now as a blessing. I used to be frustrated by it, but now I look at it as an opportunity.

R PARKER: You know, Emilie's on our mind all the time, and we see her everywhere and feel her and...

A PARKER: Having family around and being able to disconnect from the world.

R PARKER: It really does just help kind of get us grounded back into what happened and what was lost and what we had and feel sad and feel happy and cry and laugh all at the same time and just hold all those emotions.

A PARKER: And to think about our child's life is really what I want to do that day. And I'm grateful that I'm able to do it.

LEWIS: There is a ritual that we have not been doing, and that is getting a tree. And that might sound a little harsh for some people, but we had just put up our tree when Jesse was murdered, and I just couldn't find it within myself to do it again. But this year, we put up a tree. And we have plans to decorate the tree together. And so that's going to be a beautiful thing. So we'll have a tree, and this is a big - it's a big forward step for us as a family.

(SOUNDBITE OF MUSIC)

SHAPIRO: That was Scarlett Lewis, the mother of Jesse; Alissa and Robbie Parker, the parents of Emilie; Nicole Hockley, the mother of Dylan; and JoAnn Bacon, the mother of Charlotte.

SUMMERS: Bacon also serves as commissioner of the Sandy Hook Memorial that opened last month in Newtown. It's a granite fountain with each of the 26 victims' names etched in a circle. And she says she has a hope for visitors who stop to pay their respects.

BACON: I hope that they walk in a circle and say each victim's name. There is a tendency when there's these mass shootings to talk about the Sandy Hook victims as a group, but they were all unique and individual, and they all deserve to be remembered.

SHAPIRO: The victims of the Sandy Hook Elementary School shooting are - Charlotte Bacon...

SUMMERS: ...Daniel Barden...

SHAPIRO: ...Rachel D'Avino...

SUMMERS: ...Olivia Engel...

SHAPIRO: ...Josephine Gay...

SUMMERS: ...Dawn Lafferty Hochsprung...

SHAPIRO: ...Dylan Hockley...

SUMMERS: ...Madeleine Hsu...

SHAPIRO: ...Catherine Hubbard...

SUMMERS: ...Chase Kowalski...

SHAPIRO: ...Jesse Lewis...

SUMMERS: ...Ana Grace Marquez-Greene...

SHAPIRO: ...James Mattioli...

SUMMERS: ...Grace McDonnell...

SHAPIRO: ...Anne Marie Murphy....

SUMMERS: ...Emilie Parker...

SHAPIRO: ...Jack Pinto...

SUMMERS: ...Noah Pozner...

SHAPIRO: ...Caroline Previdi...

SUMMERS: ...Jessica Rekos...

SHAPIRO: ...Avielle Richman...

SUMMERS: ...Lauren Rousseau...

SHAPIRO: ...Mary Sherlach...

SUMMERS: ...Victoria Soto...

SHAPIRO: ...Benjamin Wheeler...

SUMMERS: ...And Allison Wyatt.

(SOUNDBITE OF MUSIC)

## [audio](/audio/20221214_atc_remembering_sandy_hook_shooting_victims_ten_years_later.mp3)