---
title: "Authors explain how and why to apologize the right way"
author: ''
date: "2023-01-19"
slug: ''
categories: []
tags: []
---

- I heard it from [All things considered](https://www.npr.org/2023/01/19/1150075861/authors-explain-how-and-why-to-apologize-the-right-way) 

## how to appologize: a good apology has six parts, maybe 6 1/2. 

- No. 1 is say you're sorry, not that you regret, not that you are devastated - say you're sorry.

- The second part is to say what it is that you're apologizing for. Be specific. And this is important. This gets bungled a lot. People are embarrassed. They want to get it over with. They don't want to say what they did. They say, oh, that was quite a situation. No, you got to say what it is.

- No. 3 is you've got to show you understand why it was bad, which is really difficult. You have to take ownership of the thing and show that you understand why you caused hurt.

- No. 4 is not to make excuses. Excuses can even turn into attacks. So you don't say, you know, I was having a really bad day and work was horrible and the drive home was - work was horrible. And then, you know, you asked me if I'd seen your shoes, and I'm not your shoe concierge, so of course I went off on you.

- No. 5 is say why it won't happen again. What steps are you taking?

- No. 6, if it's relevant, is to make reparation. Say, you know, I'm going to pay for the dry cleaning. Just send the bill to me. I'm going to do my best to fix what I did.

And these six steps are relevant for adults, for children, for corporations, for institutions, for governments. And 6 1/2 is listen. People want to be heard, and don't jump over them. Let the person that you hurt have their say.