---
title: "Weekly report (11/7-13)"
author: ''
date: "2022-11-12"
slug: "weekly-report-11-7-13"
categories: []
tags: []
---

- Ian won first and third place in his first swimming meet!

- Never eat salty waflle, Ina's teacher taught them to remember north, east, south and west.

- Ian asked me a question out of Genesis after his swimming: "why is the moon walking?" I tried to explained it like [this](https://coolcosmos.ipac.caltech.edu/ask/177-Why-does-the-Moon-follow-me-when-I-move-#:~:text=The%20Moon%20appears%20to%20follow,between%20you%20and%20the%20Moon.)

`The Moon appears to follow you because it is very far away, and objects like trees and houses that you pass by are very close by comparison. As you walk or drive along, things much closer to you, like trees and houses, appear to move between you and the Moon. Because the Moon is so far away, it doesn't seem to move at all (compared to you) and appears to be following you.`

But obviously, he didn't buy it: " the moon is walking even when we stop walking!" So I had to say "let's figure it out later." Two days later, when I got out of house at night, I saw the moon is walking. Suddenly, i realized that because the clouds are moving instead of the moon. 

- two interesting news which could be adapted as media articles:

  - [After being bitten by a rabid fox, a congressman wants cheaper rabies treatments](https://www.npr.org/2022/09/29/1125732515/rabies-treatment-cost-legislation)
  
  - [Congress is older than ever. It hasn't always been this way.](https://www.npr.org/2022/11/10/1135856127/congress-is-older-than-ever-it-hasnt-always-been-this-way)
  
  
- also this is very interesting:  

- [MIT Cryptoeconomics Lab](https://mitsloan.mit.edu/cryptoeconomics-lab/welcome-mit-cryptoeconomics-lab)

- [Planet Money Summer School](https://www.npr.org/podcasts/510362/planet-money-summer-school)

- [Test Your Investing Brain With The Summer School Final Quiz](https://www.npr.org/1031415672)

- 今天得知妈妈右手骨折，一个星期前发生的。