---
title: Why did you do that?
author: ''
date: '2022-10-27'
slug: why-did-you-do-that
categories: []
tags: []
---

## Why did you do that?

Josh (coach) gave each swimmer two candies since today is Halloween's week. Ian asked for two hard candies and came back to hot tub with thw candies in his hands. Since I saw Michael gave his two chocolate bars to his mom, and I wish Ian would do the same thing. To the contrary, he even did not give them to even I said :

"I can keep them for you and you could eat it later."

Somehow, he put the candies into the water. I think the water is too dirty, and insisted that I would keep the candies for him. He totally ignored what I said and kept trying to open the candy. It's about two minutes before he finally open the candy. I just cannot hold it myself and scraped the candies from his hands by force. Immediately, I threw the opened candy into the trash can.

Michael saw it and ask the question:

"Why did you do that?"

I just realized that I cannot answer the question; Ian was very upset and we went to the shower room quickly.

It's very sad to me: I cannot teach Ian to behave in the good way as Michael did. But there is a good news: it seems like I has improved a little bit of his diving.